version: '3.4'
services:
  {{ NAME }}:
    image: {{ IMAGE }}
    deploy:
      resources:
        limits:
          cpus: "{{ CPU }}"
          memory: "{{ MEMORY }}"
    restart: always
    container_name: {{ NAME }}
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - /etc/localtime:/etc/localtime
    ports:
      - "81:80/tcp"
    logging:
      driver: "json-file"
      options:
        max-size: "5M"
        max-file: "10"
    environment:
      TZ: "Asia/Shanghai"
    healthcheck:
      test: curl --fail http://localhost:80/ || exit 1
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 10s
    networks:
      - network1
  {{ EXPORTER_NAME }}:
    image: {{ EXPORTER_IMAGE }}
    container_name: {{ EXPORTER_NAME }}
    command: --nginx.scrape-uri=http://{{ NAME }}:8080/stub_status
    deploy:
      resources:
        limits:
          cpus: "{{ EXPORTER_CPU }}"
          memory: "{{ EXPORTER_MEMORY }}"
    ports:
      - "{{ EXPORTER_PORT }}:9113"
    environment:
      TZ: "Asia/Shanghai"
    healthcheck:
      test: wget http://localhost:9113/metrics -O /dev/null || exit 1
      interval: 10s
      retries: 5
      timeout: 10s
      start_period: 10s
    depends_on:
      - {{ NAME }}
    networks:
      - network1
networks:
  network1:
    external: true
    name: {{ NETWORK_NAME }}
