version: '3.4'
services:
  {{ NAME }}:
    image: {{ IMAGE }}
    deploy:
      resources:
        limits:
          cpus: "{{ CPU }}"
          memory: "{{ MEMORY }}"
    restart: always
    container_name: {{ NAME }}
    environment:
      - TZ=Asia/Shanghai
    labels:
      mz-app.platform: "mz"
      mz-app.type: "system"
      mz-app.service: "mz-"
      mz-app.metric: "{{ PORT }}"
    hostname: {{ NAME }}
    volumes:
      - ./data:/var/lib/registry
      - ./config/config.yml:/etc/distribution/config.yml
      - ./config/.pass:/etc/distribution/.passwd
    ports:
      - "{{ PORT }}:5000/tcp"
    logging:
      driver: "json-file"
      options:
        max-size: "5M"
        max-file: "10"
    healthcheck:
      test: wget --spider  127.0.0.1:5000/v2  || exit 1
      interval: 10s
      retries: 5
      timeout: 10s
      start_period: 10s
    networks:
      - network1
networks:
  network1:
    external: true
    name: {{ NETWORK_NAME }}
