version: '3.8'
services:
  {{ NAME }}:
    image: {{ IMAGE }}
    deploy:
      resources:
        limits:
          cpus: "{{ CPU }}"
          memory: "{{ MEMORY }}"
    restart: always
    container_name: {{ NAME }}
    environment:
      - TZ=Asia/Shanghai
    labels:
      mz-app.platform: "mz"
      mz-app.type: "system"
      mz-app.service: "mz-"
      mz-app.metric: "{{ PORT }}"
    hostname: {{ NAME }}
    volumes:
      - ./data:/nexus-data
    ports:
      - "{{ PORT }}:8081/tcp"
    logging:
      driver: "json-file"
      options:
        max-size: "5M"
        max-file: "10"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8081/-/healthy || exit 1
      interval: 10s
      retries: 5
      timeout: 10s
      start_period: 10s
    networks:
      - network1
networks:
  network1:
    external: true
    name: {{ NETWORK_NAME }}
