version: '3.4'
services:
  {{ NAME }}:
    image: {{ IMAGE }}
    deploy:
      resources:
        limits:
          cpus: "{{ CPU }}"
          memory: "{{ MEMORY }}"
    restart: always
    container_name: {{ NAME }}
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - /etc/localtime:/etc/localtime
    ports:
      - "81:80/tcp"
    logging:
      driver: "json-file"
      options:
        max-size: "5M"
        max-file: "10"
    environment:
      TZ: "Asia/Shanghai"
    healthcheck:
      test: curl --fail http://localhost:80/ || exit 1
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 10s
    networks:
      - network1
networks:
  network1:
    external: true
    name: {{ NETWORK_NAME }}
