name: CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD2 }}

      #
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: |
          echo "do run build.sh"
          export SHELL_HOME="$(pwd)/"
          bash ./docker/build/build.sh
